return {
    blacklisted = {
        [`SHAMAL`] = true,
        [`LUXOR`] = true,
        [`LUXOR2`] = true,
        [`JET`] = true,
        [`LAZER`] = true,
        [`BUZZARD`] = true,
        [`BUZZARD2`] = true,
        --[`ANNIHILATOR`] = true,
        [`ANNIHILATOR2`] = true, --
        [`SAVAGE`] = true,
        [`TITAN`] = true,
        [`RHINO`] = true,
        [`FIRETRUK`] = true,
        [`MULE`] = true,
        [`MAVERICK`] = true,
        [`BLIMP`] = true,
        [`AIRTUG`] = true,
        [`CAMPER`] = true,
        [`HYDRA`] = true,
        [`OPPRESSOR`] = true,
        [`technical3`] = true,
        [`insurgent3`] = true,
        [`insurgent`] = true, --
        [`apc`] = true,
        [`tampa3`] = true,
        [`trailersmall2`] = true,
        [`halftrack`] = true,
        [`hunter`] = true,
        [`vigilante`] = true,
        [`akula`] = true,
        [`barrage`] = true,
        [`khanjali`] = true,
        [`caracara`] = true,
        [`blimp3`] = true,
        [`menacer`] = true,
        [`oppressor2`] = true,
        [`scramjet`] = true,
        [`strikeforce`] = true,
        [`cerberus`] = true,
        [`cerberus2`] = true,
        [`cerberus3`] = true,
        [`scarab`] = true,
        [`scarab2`] = true,
        [`scarab3`] = true,
        [`rrocket`] = true,
        [`ruiner2`] = true,
        [`deluxo`] = true,
        [`zr380`] = true, --
        [`imperator`] = true, --
        [`brutus`] = true, --
        [`issi4`] = true, --
        [`issi3`] = true, --
        [`deathbike`] = true, --
        [`slamvan4`] = true, --
        [`slamvan`] = true, --
        [`monster3`] = true, --
        [`bruiser`] = true, --
        [`dominator4`] = true, --
        [`dominator`] = true, --
        [`impaler2`] = true, --
        [`impaler`] = true, --
        [`gargoyle`] = true, --
        [`ratloader2`] = true, --
        [`glendale`] = true, --
        [`ardent`] = true, --
        [`boxville5`] = true, --
        [`avenger`] = true, --
        [`blazer5`] = true, --
        [`buffalo4`] = true, --
        [`champion`] = true, --
        [`chernobog`] = true, --
        [`comet4`] = true, --
        [`deity`] = true, --
        [`dune3`] = true, --
        [`raiju`] = true, --
        [`granger2`] = true, --
        [`havok`] = true, --
        [`minitank`] = true, --
        [`jb7002`] = true, --
        [`jubilee`] = true, --
        [`kosatka`] = true, --
        [`patrolboat`] = true, --
        [`starling`] = true, --
        [`trailerlarge`] = true, --
        [`conada2`] = true, --
        [`streamer216`] = true, --
        [`ignus2`] = true, --
        [`patriot3`] = true, --
        [`dinghy5`] = true, --
        [`toreador`] = true, --
        [`seasparrow`] = true, --
        [`seasparrow2`] = true, --
        [`seasparrow3`] = true, --
        [`alkonost`] = true, --
        [`paragon2`] = true, --
        [`rcbandito`] = true, --
        [`terbyte`] = true, --
        [`speedo4`] = true, --
        [`pounder2`] = true, --
        [`mule4`] = true, --
        [`revolter`] = true, --
        [`viseris`] = true, --
        [`savestra`] = true, --
        [`thruster`] = true, --
        [`stromberg`] = true, --
        [`riot2`] = true, --
        [`volatol`] = true, --
        [`nokota`] = true, --
        [`pyro`] = true, --
        [`mogul`] = true, --
        [`bombushka`] = true, --
        [`molotok`] = true, --
        [`microlight`] = true, --
        [`tula`] = true, --
        [`rogue`] = true, --
        [`nightshark`] = true, --
        [`technical2`] = true, --
        [`technical`] = true, --
        [`limo2`] = true, --
        [`valkyrie`] = true, --
        [`s_m_y_ranger_01`] = true,
        [`s_m_y_sheriff_01`] = true,
        [`s_m_y_cop_01`] = true,
        [`s_f_y_sheriff_01`] = true,
        [`s_f_y_cop_01`] = true,
        [`s_m_y_hwaycop_01`] = true
    }
}
